### ISSUE TITLE
NoSuchElementException in tab complete causes kernel crash

### ISSUE THREAD

**Issue by amitsudharshan** [mattpap/IScala#17]
If i try and execute a tab complete, I can sometimes get the below exception. I'd be okay with tab complete failing, but would like to avoid kernel crash.

Exception in thread "RequestsEventLoop" java.util.NoSuchElementException
        at scala.collection.LinearSeqOptimized$class.last(LinearSeqOptimized.scala:134)
        at scala.collection.immutable.List.last(List.scala:83)
        at org.refptr.iscala.IScalaCompletion$literals$.simpleParse(Completion.scala:199)
        at org.refptr.iscala.IScalaCompletion$literals$.follow(Completion.scala:202)
        at org.refptr.iscala.CompletionAware$class.completionsFor(Completion.scala:29)
        at org.refptr.iscala.IScalaCompletion$literals$.completionsFor(Completion.scala:198)
        at org.refptr.iscala.IScalaCompletion$$anonfun$topLevelFor$1.apply(Completion.scala:229)
        at org.refptr.iscala.IScalaCompletion$$anonfun$topLevelFor$1.apply(Completion.scala:229)
        at scala.collection.immutable.List.flatMap(List.scala:327)
        at org.refptr.iscala.IScalaCompletion.topLevelFor(Completion.scala:229)
        at org.refptr.iscala.IScalaCompletion.completions(Completion.scala:232)
        at org.refptr.iscala.CompleteHandler.apply(Handlers.scala:121)
        at org.refptr.iscala.IScala$EventLoop.dispatch(IScala.scala:127)
        at org.refptr.iscala.IScala$EventLoop$$anonfun$run$2.apply(IScala.scala:139)
        at org.refptr.iscala.IScala$EventLoop$$anonfun$run$2.apply(IScala.scala:139)
        at scala.Option.foreach(Option.scala:245)
        at org.refptr.iscala.IScala$EventLoop.run(IScala.scala:139)

**Comment by mattpap** [comment]
Fixed in bcfa37a.
